#
# WARN: not yet set up, misses credentials setup etc on travis
#

dist: trusty
sudo: false

language: java

env:
  global:
  - MAVEN_OPTS="-Dsurefire.useFile=false -Dmaven.artifact.threads=128 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  - SKIP_OPTS="-Dcheckstyle.skip=true -Drat.skip=true -DskipTests"
  - BUILD_ARGS="clean install -B -q -e"

before_cache:
- rm -Rf $HOME/.m2/repository/com/github/rmannibucau
cache:
  timeout: 1000
  directories:
  - "$HOME/.m2"

install: echo true

jobs:
  include:
  # PR profile
  - stage: pullrequest_build
    script: mvn $BUILD_ARGS
    jdk: openjdk11

  # master profile
  - stage: master_build
    env:
    - STEP=Build OpenJDK 11 JVM
    script: mvn $BUILD_ARGS -Premote-docker -Ddocker.registry=registry.hub.docker.com/
    jdk: openjdk11

  - stage: master_build
    env:
    - STEP=Sonatype Audit
    script: mvn clean install -B -q -e -DskipTests && travis_wait 15 mvn ossindex:audit -B
    jdk: openjdk11

stages:
- name: master_build
  if: branch = master AND type != pull_request
- name: pullrequest_build
  if: type = pull_request
